version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=chatterdb
    command: mongod --noauth --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  # You can add more services here, for example a backend API:
  # api:
  #   build: ./api
  #   container_name: api
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - MONGO_URI=mongodb://admin:password@mongodb:27017/mydatabase
  #   networks:
  #     - app-network

volumes:
  mongodb-data:
    driver: local

networks:
  app-network:
    driver: bridge